package org.postgresql.db {
    /**
     * Class describing a field of data in an IResultSet.
     */
    public interface IColumn {
        /**
         * The name of this column: either the alias specified in the target
         * list of the query, or the name generated by PostgreSQL if no
         * alias was used.
         */
        function get name():String;
        /**
         * The client-side data type of the column. This is determined by the
         * OID of the column's (server-side) data type and the decoder registered
         * for that data type in the current configuration.
         */
        function get type():Class;
        /**
         * The OID of the column's actual, server-side data type.
         */
        function get typeOid():int;
    }
}